### PR TITLE
Explicit windows test case for Java test path logic

### LINKED ISSUE #159: https://github.com/symflower/eval-dev-quality/pull/155/files missing a test
All change need tests in TDD style. fail first, pass with changes. Same rules as internally.

### PR DESCRIPTION
**Pull request by bauersimon**
Closes #159

### CODE REVIEW

File: language/java/language_test.go [hunk 1]
```diff
@@ -113,13 +113,23 @@ func TestLanguageTestFilePath(t *testing.T) {
 		})
 	}
 
-	validate(t, &testCase{
-		Name: "Source file",
+	if !osutil.IsWindows() {
```
Comment (Munsio) [inline language/java/language_test.go:116]: Just a nitpick but would remove the negation and swap the condition content. When skimming over code it is easier having a `true` case.
